# Repositorio de productos
repository.productos.type=csv
repository.productos.path=data/productos.csv

# Repositorio de vehículos
repository.vehiculos.type=json
repository.vehiculos.path=data/vehiculos.json
